apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: loggen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: chentex/random-logger:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
        # Define environment variables if needed
        env:
        - name: LOG_LEVEL
          value: "info"
        # You may need to mount volumes if you want to store logs persistently
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: log-volume
        emptyDir: {}
