apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-els
  labels:
    app: elasticsearch
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 10Gi
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/sidhu/allclones/datadir/elasticsearch
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-logstash
#   labels:
#     app: logstash
# spec:
#   accessModes:
#     - "ReadWriteOnce"
#   capacity:
#     storage: 5Gi
#   storageClassName: hostpath
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /home/sidhu/allclones/datadir/logstash

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-kibana
#   labels:
#     app: kibana
# spec:
#   accessModes:
#     - "ReadWriteOnce"
#   capacity:
#     storage: 5Gi
#   storageClassName: hostpath
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /home/sidhu/allclones/datadir/kibana
