apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      beats {
        port => "5044"
      }
    }
    filter {
      grok {
          match => { "message" => "%{COMBINEDAPACHELOG}"}
      }
      geoip {
          source => "clientip"
          ecs_compatibility => disabled
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
    }
